import pandas as pd
planet1df = pd.read_csv("updated_scraped_data.csv")
planet2df = pd.read_csv("new_scraped_data.csv")
print (planet1df.head())
print (planet2df.head())
planet2df.drop(columns = ['discovery_date', 'mass', 'detection_method'],inplace=True)
headers = ['name' ,'light_years_from_earth', 'planet_mass', 'stellar_magnitude','discovery_date', 'hyperlink','planet_type' ,'planet_radius', 'orbital_radius', 'orbital_period' ,'eccentricity']
finaldf = pd.DataFrame(columns = headers)
finaldf = pd.merge(planet1df,planet2df)
#finaldf.to_csv()
finaldf = pd.read_csv("final_scraped_data.csv")
planet3df = pd.read_csv("PSCompPars.csv")
planet3df["pl_name"] = planet3df['pl_name'].str.lower()
print(planet3df.head())
print(finaldf.shape)
print(planet3df.shape)
planet3df = planet3df.sort_values("pl_name")
mergedf = pd.merge(finaldf,planet3df,on = "id")
print(mergedf.shape)
mergedf.to_csv("mergeplanets.csv")